import assets from "../assets";

export const colorsAndShapes = [
  { id: 1, color: "Apple", shape: "Circle", image: assets.images.colorsAndShapes.Apple.Circle },
  { id: 2, color: "Apple", shape: "Octagon", image: assets.images.colorsAndShapes.Apple.Octagon },
  {
    id: 3,
    color: "Apple",
    shape: "Hexadecagon",
    image: assets.images.colorsAndShapes.Apple.Hexadecagon,
  },
  {
    id: 4,
    color: "Apple",
    shape: "Hexadecagon",
    image: assets.images.colorsAndShapes.Apple.Square,
  },
  {
    id: 5,
    color: "ButtonBlue",
    shape: "Circle",
    image: assets.images.colorsAndShapes.ButtonBlue.Circle,
  },
  {
    id: 6,
    color: "ButtonBlue",
    shape: "Octagon",
    image: assets.images.colorsAndShapes.ButtonBlue.Octagon,
  },
  {
    id: 7,
    color: "ButtonBlue",
    shape: "Hexadecagon",
    image: assets.images.colorsAndShapes.ButtonBlue.Hexadecagon,
  },
  {
    id: 8,
    color: "ButtonBlue",
    shape: "Square",
    image: assets.images.colorsAndShapes.ButtonBlue.Square,
  },
  {
    id: 9,
    color: "CoralRedCircle",
    shape: "Circle",
    image: assets.images.colorsAndShapes.CoralRedCircle.Circle,
  },
  {
    id: 10,
    color: "CoralRedCircle",
    shape: "Octagon",
    image: assets.images.colorsAndShapes.CoralRedCircle.Octagon,
  },
  {
    id: 11,
    color: "CoralRedCircle",
    shape: "Hexadecagon",
    image: assets.images.colorsAndShapes.CoralRedCircle.Hexadecagon,
  },
  {
    id: 12,
    color: "CoralRedCircle",
    shape: "Square",
    image: assets.images.colorsAndShapes.CoralRedCircle.Square,
  },
  {
    id: 13,
    color: "Razzmatazz",
    shape: "Circle",
    image: assets.images.colorsAndShapes.Razzmatazz.Circle,
  },
  {
    id: 14,
    color: "Razzmatazz",
    shape: "Octagon",
    image: assets.images.colorsAndShapes.Razzmatazz.Octagon,
  },
  {
    id: 15,
    color: "Razzmatazz",
    shape: "Hexadecagon",
    image: assets.images.colorsAndShapes.Razzmatazz.Hexadecagon,
  },
  {
    id: 16,
    color: "Razzmatazz",
    shape: "Square",
    image: assets.images.colorsAndShapes.Razzmatazz.Square,
  },
  {
    id: 17,
    color: "Pear",
    shape: "Circle",
    image: assets.images.colorsAndShapes.Pear.Circle,
  },
  {
    id: 18,
    color: "Pear",
    shape: "Octagon",
    image: assets.images.colorsAndShapes.Pear.Octagon,
  },
  {
    id: 19,
    color: "Pear",
    shape: "Hexadecagon",
    image: assets.images.colorsAndShapes.Pear.Hexadecagon,
  },
  {
    id: 20,
    color: "Pear",
    shape: "Square",
    image: assets.images.colorsAndShapes.Pear.Square,
  },
  {
    id: 21,
    color: "DarkOrchid",
    shape: "Circle",
    image: assets.images.colorsAndShapes.DarkOrchid.Circle,
  },
  {
    id: 22,
    color: "DarkOrchid",
    shape: "Octagon",
    image: assets.images.colorsAndShapes.DarkOrchid.Octagon,
  },
  {
    id: 23,
    color: "DarkOrchid",
    shape: "Hexadecagon",
    image: assets.images.colorsAndShapes.DarkOrchid.Hexadecagon,
  },
  {
    id: 24,
    color: "DarkOrchid",
    shape: "Square",
    image: assets.images.colorsAndShapes.DarkOrchid.Square,
  },
  {
    id: 25,
    color: "SoftPeach",
    shape: "Circle",
    image: assets.images.colorsAndShapes.SoftPeach.Circle,
  },
  {
    id: 26,
    color: "SoftPeach",
    shape: "Octagon",
    image: assets.images.colorsAndShapes.SoftPeach.Hexadecagon,
  },
  {
    id: 27,
    color: "SoftPeach",
    shape: "Hexadecagon",
    image: assets.images.colorsAndShapes.SoftPeach.Hexadecagon,
  },
  {
    id: 28,
    color: "SoftPeach",
    shape: "Square",
    image: assets.images.colorsAndShapes.SoftPeach.Square,
  },
  {
    id: 29,
    color: "SoftPeach",
    shape: "BorderSquare2",
    image: assets.images.colorsAndShapes.SoftPeach.BorderSquare2,
  },
  {
    id: 30,
    color: "SoftPeach",
    shape: "BorderSquare3",
    image: assets.images.colorsAndShapes.SoftPeach.BorderSquare3,
  },
];

export const itemList = [
  {
    id: 1,
    productName: "Item 1",
    backgroundImage: "",
    color: "",
    shape: "",
  },
  {
    id: 2,
    productName: "Item 2",
    backgroundImage: "https://images.unsplash.com/photo-1516802273409-68526ee1bdd6",
    color: "",
    shape: "",
  },
  {
    id: 3,
    productName: "Item 3",
    backgroundImage: "",
    color: "Razzmatazz",
    shape: "Octagon",
  },
  {
    id: 4,
    productName: "Item 4",
    backgroundImage: "",
    color: "CoralRedCircle",
    shape: "Circle",
  },
  {
    id: 5,
    productName: "Item 5",
    backgroundImage: "",
    color: "Pear",
    shape: "Hexadecagon",
  },
  {
    id: 6,
    productName: "Item 6",
    backgroundImage: "",
    color: "CoralRedCircle",
    shape: "Circle",
  },
  {
    id: 7,
    productName: "Item 7",
    backgroundImage: "",
    color: "Pear",
    shape: "Octagon",
  },
  {
    id: 8,
    productName: "Item 8",
    backgroundImage: "https://images.unsplash.com/photo-1516802273409-68526ee1bdd6",
    color: "SoftPeach",
    shape: "Octagon",
  },
];
